#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR/../..

export JAVA_OPTS="-Djava.library.path=/Users/salman/code/hops/rondb21/build/lib"
./bin/ycsb run rondb -s -P ./workloads/workloadc \
       -p "rondb.connection.string=localhost:13000" \
       -p "rondb.schema=ycsb" \
       -p "rondb.read.api.type=clusterj" \
       -p "fieldcount=10"  \
       -p "fieldlength=100" \
       -p "fieldnameprefix=FIELD" \
       -p "threadcount=100" \
       -p "readBatchSize=3"


