#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR/../..

export JAVA_OPTS="-Djava.library.path=/Users/salman/code/hops/rondb21/build/lib"

./bin/ycsb run rondb -s -P ./workloads/workloada \
    -p "rondb.connection.string=localhost:13000" \
    -p "rondb.schema=ycsb" \
    -p "rondb.read.api.type=GRPC" \
    -p "rondb.api.server.ip=127.0.0.1" \
    -p "rondb.api.server.rest.port=5406" \
    -p "fieldcount=10"  \
    -p "fieldlength=100" \
    -p "fieldnameprefix=FIELD" \
    -p "threadcount=10" \
    -p "readBatchSize=5" \
    -p "updateBatchSize=5"

